server:
  port: 8000
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/timf
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug