server:
  port: 8000
spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/timf
    url: jdbc:h2:mem:timf
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
